apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
data:
  JWT_SECRET: eW91ci1zZWNyZXQta2V5  # base64 encoded
  MONGODB_USERNAME: YWRtaW4=  # base64 encoded 'admin'
  MONGODB_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
